# This file is auto generated by `vim-mode-plus:write-command-table-on-disk` command.
# DONT edit manually.
module.exports =
Operator:
  file: "./operator"
Select:
  file: "./operator"
SelectLatestChange:
  file: "./operator"
  commandName: "vim-mode-plus:select-latest-change"
  commandScope: "atom-text-editor"
SelectPreviousSelection:
  file: "./operator"
  commandName: "vim-mode-plus:select-previous-selection"
  commandScope: "atom-text-editor"
SelectPersistentSelection:
  file: "./operator"
  commandName: "vim-mode-plus:select-persistent-selection"
  commandScope: "atom-text-editor"
SelectOccurrence:
  file: "./operator"
  commandName: "vim-mode-plus:select-occurrence"
  commandScope: "atom-text-editor"
CreatePersistentSelection:
  file: "./operator"
  commandName: "vim-mode-plus:create-persistent-selection"
  commandScope: "atom-text-editor"
TogglePersistentSelection:
  file: "./operator"
  commandName: "vim-mode-plus:toggle-persistent-selection"
  commandScope: "atom-text-editor"
TogglePresetOccurrence:
  file: "./operator"
  commandName: "vim-mode-plus:toggle-preset-occurrence"
  commandScope: "atom-text-editor"
TogglePresetSubwordOccurrence:
  file: "./operator"
  commandName: "vim-mode-plus:toggle-preset-subword-occurrence"
  commandScope: "atom-text-editor"
AddPresetOccurrenceFromLastOccurrencePattern:
  file: "./operator"
  commandName: "vim-mode-plus:add-preset-occurrence-from-last-occurrence-pattern"
  commandScope: "atom-text-editor"
Delete:
  file: "./operator"
  commandName: "vim-mode-plus:delete"
  commandScope: "atom-text-editor"
DeleteRight:
  file: "./operator"
  commandName: "vim-mode-plus:delete-right"
  commandScope: "atom-text-editor"
DeleteLeft:
  file: "./operator"
  commandName: "vim-mode-plus:delete-left"
  commandScope: "atom-text-editor"
DeleteToLastCharacterOfLine:
  file: "./operator"
  commandName: "vim-mode-plus:delete-to-last-character-of-line"
  commandScope: "atom-text-editor"
DeleteLine:
  file: "./operator"
  commandName: "vim-mode-plus:delete-line"
  commandScope: "atom-text-editor"
Yank:
  file: "./operator"
  commandName: "vim-mode-plus:yank"
  commandScope: "atom-text-editor"
YankLine:
  file: "./operator"
  commandName: "vim-mode-plus:yank-line"
  commandScope: "atom-text-editor"
YankToLastCharacterOfLine:
  file: "./operator"
  commandName: "vim-mode-plus:yank-to-last-character-of-line"
  commandScope: "atom-text-editor"
Increase:
  file: "./operator"
  commandName: "vim-mode-plus:increase"
  commandScope: "atom-text-editor"
Decrease:
  file: "./operator"
  commandName: "vim-mode-plus:decrease"
  commandScope: "atom-text-editor"
IncrementNumber:
  file: "./operator"
  commandName: "vim-mode-plus:increment-number"
  commandScope: "atom-text-editor"
DecrementNumber:
  file: "./operator"
  commandName: "vim-mode-plus:decrement-number"
  commandScope: "atom-text-editor"
PutBefore:
  file: "./operator"
  commandName: "vim-mode-plus:put-before"
  commandScope: "atom-text-editor"
PutAfter:
  file: "./operator"
  commandName: "vim-mode-plus:put-after"
  commandScope: "atom-text-editor"
PutBeforeWithAutoIndent:
  file: "./operator"
  commandName: "vim-mode-plus:put-before-with-auto-indent"
  commandScope: "atom-text-editor"
PutAfterWithAutoIndent:
  file: "./operator"
  commandName: "vim-mode-plus:put-after-with-auto-indent"
  commandScope: "atom-text-editor"
AddBlankLineBelow:
  file: "./operator"
  commandName: "vim-mode-plus:add-blank-line-below"
  commandScope: "atom-text-editor"
AddBlankLineAbove:
  file: "./operator"
  commandName: "vim-mode-plus:add-blank-line-above"
  commandScope: "atom-text-editor"
ActivateInsertMode:
  file: "./operator-insert"
  commandName: "vim-mode-plus:activate-insert-mode"
  commandScope: "atom-text-editor"
ActivateReplaceMode:
  file: "./operator-insert"
  commandName: "vim-mode-plus:activate-replace-mode"
  commandScope: "atom-text-editor"
InsertAfter:
  file: "./operator-insert"
  commandName: "vim-mode-plus:insert-after"
  commandScope: "atom-text-editor"
InsertAtBeginningOfLine:
  file: "./operator-insert"
  commandName: "vim-mode-plus:insert-at-beginning-of-line"
  commandScope: "atom-text-editor"
InsertAfterEndOfLine:
  file: "./operator-insert"
  commandName: "vim-mode-plus:insert-after-end-of-line"
  commandScope: "atom-text-editor"
InsertAtFirstCharacterOfLine:
  file: "./operator-insert"
  commandName: "vim-mode-plus:insert-at-first-character-of-line"
  commandScope: "atom-text-editor"
InsertAtLastInsert:
  file: "./operator-insert"
  commandName: "vim-mode-plus:insert-at-last-insert"
  commandScope: "atom-text-editor"
InsertAboveWithNewline:
  file: "./operator-insert"
  commandName: "vim-mode-plus:insert-above-with-newline"
  commandScope: "atom-text-editor"
InsertBelowWithNewline:
  file: "./operator-insert"
  commandName: "vim-mode-plus:insert-below-with-newline"
  commandScope: "atom-text-editor"
InsertByTarget:
  file: "./operator-insert"
InsertAtStartOfTarget:
  file: "./operator-insert"
  commandName: "vim-mode-plus:insert-at-start-of-target"
  commandScope: "atom-text-editor"
InsertAtEndOfTarget:
  file: "./operator-insert"
  commandName: "vim-mode-plus:insert-at-end-of-target"
  commandScope: "atom-text-editor"
InsertAtStartOfOccurrence:
  file: "./operator-insert"
  commandName: "vim-mode-plus:insert-at-start-of-occurrence"
  commandScope: "atom-text-editor"
InsertAtEndOfOccurrence:
  file: "./operator-insert"
  commandName: "vim-mode-plus:insert-at-end-of-occurrence"
  commandScope: "atom-text-editor"
InsertAtStartOfSubwordOccurrence:
  file: "./operator-insert"
  commandName: "vim-mode-plus:insert-at-start-of-subword-occurrence"
  commandScope: "atom-text-editor"
InsertAtEndOfSubwordOccurrence:
  file: "./operator-insert"
  commandName: "vim-mode-plus:insert-at-end-of-subword-occurrence"
  commandScope: "atom-text-editor"
InsertAtStartOfSmartWord:
  file: "./operator-insert"
  commandName: "vim-mode-plus:insert-at-start-of-smart-word"
  commandScope: "atom-text-editor"
InsertAtEndOfSmartWord:
  file: "./operator-insert"
  commandName: "vim-mode-plus:insert-at-end-of-smart-word"
  commandScope: "atom-text-editor"
InsertAtPreviousFoldStart:
  file: "./operator-insert"
  commandName: "vim-mode-plus:insert-at-previous-fold-start"
  commandScope: "atom-text-editor"
InsertAtNextFoldStart:
  file: "./operator-insert"
  commandName: "vim-mode-plus:insert-at-next-fold-start"
  commandScope: "atom-text-editor"
Change:
  file: "./operator-insert"
  commandName: "vim-mode-plus:change"
  commandScope: "atom-text-editor"
ChangeOccurrence:
  file: "./operator-insert"
  commandName: "vim-mode-plus:change-occurrence"
  commandScope: "atom-text-editor"
Substitute:
  file: "./operator-insert"
  commandName: "vim-mode-plus:substitute"
  commandScope: "atom-text-editor"
SubstituteLine:
  file: "./operator-insert"
  commandName: "vim-mode-plus:substitute-line"
  commandScope: "atom-text-editor"
ChangeLine:
  file: "./operator-insert"
  commandName: "vim-mode-plus:change-line"
  commandScope: "atom-text-editor"
ChangeToLastCharacterOfLine:
  file: "./operator-insert"
  commandName: "vim-mode-plus:change-to-last-character-of-line"
  commandScope: "atom-text-editor"
TransformString:
  file: "./operator-transform-string"
ToggleCase:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:toggle-case"
  commandScope: "atom-text-editor"
ToggleCaseAndMoveRight:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:toggle-case-and-move-right"
  commandScope: "atom-text-editor"
UpperCase:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:upper-case"
  commandScope: "atom-text-editor"
LowerCase:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:lower-case"
  commandScope: "atom-text-editor"
Replace:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:replace"
  commandScope: "atom-text-editor"
ReplaceCharacter:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:replace-character"
  commandScope: "atom-text-editor"
SplitByCharacter:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:split-by-character"
  commandScope: "atom-text-editor"
CamelCase:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:camel-case"
  commandScope: "atom-text-editor"
SnakeCase:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:snake-case"
  commandScope: "atom-text-editor"
PascalCase:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:pascal-case"
  commandScope: "atom-text-editor"
DashCase:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:dash-case"
  commandScope: "atom-text-editor"
TitleCase:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:title-case"
  commandScope: "atom-text-editor"
EncodeUriComponent:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:encode-uri-component"
  commandScope: "atom-text-editor"
DecodeUriComponent:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:decode-uri-component"
  commandScope: "atom-text-editor"
TrimString:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:trim-string"
  commandScope: "atom-text-editor"
CompactSpaces:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:compact-spaces"
  commandScope: "atom-text-editor"
RemoveLeadingWhiteSpaces:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:remove-leading-white-spaces"
  commandScope: "atom-text-editor"
ConvertToSoftTab:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:convert-to-soft-tab"
  commandScope: "atom-text-editor"
ConvertToHardTab:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:convert-to-hard-tab"
  commandScope: "atom-text-editor"
TransformStringByExternalCommand:
  file: "./operator-transform-string"
TransformStringBySelectList:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:transform-string-by-select-list"
  commandScope: "atom-text-editor"
TransformWordBySelectList:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:transform-word-by-select-list"
  commandScope: "atom-text-editor"
TransformSmartWordBySelectList:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:transform-smart-word-by-select-list"
  commandScope: "atom-text-editor"
ReplaceWithRegister:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:replace-with-register"
  commandScope: "atom-text-editor"
SwapWithRegister:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:swap-with-register"
  commandScope: "atom-text-editor"
Indent:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:indent"
  commandScope: "atom-text-editor"
Outdent:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:outdent"
  commandScope: "atom-text-editor"
AutoIndent:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:auto-indent"
  commandScope: "atom-text-editor"
ToggleLineComments:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:toggle-line-comments"
  commandScope: "atom-text-editor"
Reflow:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:reflow"
  commandScope: "atom-text-editor"
ReflowWithStay:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:reflow-with-stay"
  commandScope: "atom-text-editor"
SurroundBase:
  file: "./operator-transform-string"
Surround:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:surround"
  commandScope: "atom-text-editor"
SurroundWord:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:surround-word"
  commandScope: "atom-text-editor"
SurroundSmartWord:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:surround-smart-word"
  commandScope: "atom-text-editor"
MapSurround:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:map-surround"
  commandScope: "atom-text-editor"
DeleteSurround:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:delete-surround"
  commandScope: "atom-text-editor"
DeleteSurroundAnyPair:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:delete-surround-any-pair"
  commandScope: "atom-text-editor"
DeleteSurroundAnyPairAllowForwarding:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:delete-surround-any-pair-allow-forwarding"
  commandScope: "atom-text-editor"
ChangeSurround:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:change-surround"
  commandScope: "atom-text-editor"
ChangeSurroundAnyPair:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:change-surround-any-pair"
  commandScope: "atom-text-editor"
ChangeSurroundAnyPairAllowForwarding:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:change-surround-any-pair-allow-forwarding"
  commandScope: "atom-text-editor"
Join:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:join"
  commandScope: "atom-text-editor"
JoinBase:
  file: "./operator-transform-string"
JoinWithKeepingSpace:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:join-with-keeping-space"
  commandScope: "atom-text-editor"
JoinByInput:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:join-by-input"
  commandScope: "atom-text-editor"
JoinByInputWithKeepingSpace:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:join-by-input-with-keeping-space"
  commandScope: "atom-text-editor"
SplitString:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:split-string"
  commandScope: "atom-text-editor"
SplitStringWithKeepingSplitter:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:split-string-with-keeping-splitter"
  commandScope: "atom-text-editor"
SplitArguments:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:split-arguments"
  commandScope: "atom-text-editor"
SplitArgumentsWithRemoveSeparator:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:split-arguments-with-remove-separator"
  commandScope: "atom-text-editor"
SplitArgumentsOfInnerAnyPair:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:split-arguments-of-inner-any-pair"
  commandScope: "atom-text-editor"
ChangeOrder:
  file: "./operator-transform-string"
Reverse:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:reverse"
  commandScope: "atom-text-editor"
ReverseInnerAnyPair:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:reverse-inner-any-pair"
  commandScope: "atom-text-editor"
Rotate:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:rotate"
  commandScope: "atom-text-editor"
RotateBackwards:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:rotate-backwards"
  commandScope: "atom-text-editor"
RotateArgumentsOfInnerPair:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:rotate-arguments-of-inner-pair"
  commandScope: "atom-text-editor"
RotateArgumentsBackwardsOfInnerPair:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:rotate-arguments-backwards-of-inner-pair"
  commandScope: "atom-text-editor"
Sort:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:sort"
  commandScope: "atom-text-editor"
SortCaseInsensitively:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:sort-case-insensitively"
  commandScope: "atom-text-editor"
SortByNumber:
  file: "./operator-transform-string"
  commandName: "vim-mode-plus:sort-by-number"
  commandScope: "atom-text-editor"
Motion:
  file: "./motion"
CurrentSelection:
  file: "./motion"
MoveLeft:
  file: "./motion"
  commandName: "vim-mode-plus:move-left"
  commandScope: "atom-text-editor"
MoveRight:
  file: "./motion"
  commandName: "vim-mode-plus:move-right"
  commandScope: "atom-text-editor"
MoveRightBufferColumn:
  file: "./motion"
MoveUp:
  file: "./motion"
  commandName: "vim-mode-plus:move-up"
  commandScope: "atom-text-editor"
MoveUpWrap:
  file: "./motion"
  commandName: "vim-mode-plus:move-up-wrap"
  commandScope: "atom-text-editor"
MoveDown:
  file: "./motion"
  commandName: "vim-mode-plus:move-down"
  commandScope: "atom-text-editor"
MoveDownWrap:
  file: "./motion"
  commandName: "vim-mode-plus:move-down-wrap"
  commandScope: "atom-text-editor"
MoveUpScreen:
  file: "./motion"
  commandName: "vim-mode-plus:move-up-screen"
  commandScope: "atom-text-editor"
MoveDownScreen:
  file: "./motion"
  commandName: "vim-mode-plus:move-down-screen"
  commandScope: "atom-text-editor"
MoveUpToEdge:
  file: "./motion"
  commandName: "vim-mode-plus:move-up-to-edge"
  commandScope: "atom-text-editor"
MoveDownToEdge:
  file: "./motion"
  commandName: "vim-mode-plus:move-down-to-edge"
  commandScope: "atom-text-editor"
MoveToNextWord:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-next-word"
  commandScope: "atom-text-editor"
MoveToPreviousWord:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-previous-word"
  commandScope: "atom-text-editor"
MoveToEndOfWord:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-end-of-word"
  commandScope: "atom-text-editor"
MoveToPreviousEndOfWord:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-previous-end-of-word"
  commandScope: "atom-text-editor"
MoveToNextWholeWord:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-next-whole-word"
  commandScope: "atom-text-editor"
MoveToPreviousWholeWord:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-previous-whole-word"
  commandScope: "atom-text-editor"
MoveToEndOfWholeWord:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-end-of-whole-word"
  commandScope: "atom-text-editor"
MoveToPreviousEndOfWholeWord:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-previous-end-of-whole-word"
  commandScope: "atom-text-editor"
MoveToNextAlphanumericWord:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-next-alphanumeric-word"
  commandScope: "atom-text-editor"
MoveToPreviousAlphanumericWord:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-previous-alphanumeric-word"
  commandScope: "atom-text-editor"
MoveToEndOfAlphanumericWord:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-end-of-alphanumeric-word"
  commandScope: "atom-text-editor"
MoveToNextSmartWord:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-next-smart-word"
  commandScope: "atom-text-editor"
MoveToPreviousSmartWord:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-previous-smart-word"
  commandScope: "atom-text-editor"
MoveToEndOfSmartWord:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-end-of-smart-word"
  commandScope: "atom-text-editor"
MoveToNextSubword:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-next-subword"
  commandScope: "atom-text-editor"
MoveToPreviousSubword:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-previous-subword"
  commandScope: "atom-text-editor"
MoveToEndOfSubword:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-end-of-subword"
  commandScope: "atom-text-editor"
MoveToNextSentence:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-next-sentence"
  commandScope: "atom-text-editor"
MoveToPreviousSentence:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-previous-sentence"
  commandScope: "atom-text-editor"
MoveToNextSentenceSkipBlankRow:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-next-sentence-skip-blank-row"
  commandScope: "atom-text-editor"
MoveToPreviousSentenceSkipBlankRow:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-previous-sentence-skip-blank-row"
  commandScope: "atom-text-editor"
MoveToNextParagraph:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-next-paragraph"
  commandScope: "atom-text-editor"
MoveToPreviousParagraph:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-previous-paragraph"
  commandScope: "atom-text-editor"
MoveToBeginningOfLine:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-beginning-of-line"
  commandScope: "atom-text-editor"
MoveToColumn:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-column"
  commandScope: "atom-text-editor"
MoveToLastCharacterOfLine:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-last-character-of-line"
  commandScope: "atom-text-editor"
MoveToLastNonblankCharacterOfLineAndDown:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-last-nonblank-character-of-line-and-down"
  commandScope: "atom-text-editor"
MoveToFirstCharacterOfLine:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-first-character-of-line"
  commandScope: "atom-text-editor"
MoveToFirstCharacterOfLineUp:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-first-character-of-line-up"
  commandScope: "atom-text-editor"
MoveToFirstCharacterOfLineDown:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-first-character-of-line-down"
  commandScope: "atom-text-editor"
MoveToFirstCharacterOfLineAndDown:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-first-character-of-line-and-down"
  commandScope: "atom-text-editor"
MoveToFirstLine:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-first-line"
  commandScope: "atom-text-editor"
MoveToLastLine:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-last-line"
  commandScope: "atom-text-editor"
MoveToLineByPercent:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-line-by-percent"
  commandScope: "atom-text-editor"
MoveToRelativeLine:
  file: "./motion"
MoveToRelativeLineMinimumOne:
  file: "./motion"
MoveToTopOfScreen:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-top-of-screen"
  commandScope: "atom-text-editor"
MoveToMiddleOfScreen:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-middle-of-screen"
  commandScope: "atom-text-editor"
MoveToBottomOfScreen:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-bottom-of-screen"
  commandScope: "atom-text-editor"
Scroll:
  file: "./motion"
ScrollFullScreenDown:
  file: "./motion"
  commandName: "vim-mode-plus:scroll-full-screen-down"
  commandScope: "atom-text-editor"
ScrollFullScreenUp:
  file: "./motion"
  commandName: "vim-mode-plus:scroll-full-screen-up"
  commandScope: "atom-text-editor"
ScrollHalfScreenDown:
  file: "./motion"
  commandName: "vim-mode-plus:scroll-half-screen-down"
  commandScope: "atom-text-editor"
ScrollHalfScreenUp:
  file: "./motion"
  commandName: "vim-mode-plus:scroll-half-screen-up"
  commandScope: "atom-text-editor"
Find:
  file: "./motion"
  commandName: "vim-mode-plus:find"
  commandScope: "atom-text-editor"
FindBackwards:
  file: "./motion"
  commandName: "vim-mode-plus:find-backwards"
  commandScope: "atom-text-editor"
Till:
  file: "./motion"
  commandName: "vim-mode-plus:till"
  commandScope: "atom-text-editor"
TillBackwards:
  file: "./motion"
  commandName: "vim-mode-plus:till-backwards"
  commandScope: "atom-text-editor"
MoveToMark:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-mark"
  commandScope: "atom-text-editor"
MoveToMarkLine:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-mark-line"
  commandScope: "atom-text-editor"
MoveToPreviousFoldStart:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-previous-fold-start"
  commandScope: "atom-text-editor"
MoveToNextFoldStart:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-next-fold-start"
  commandScope: "atom-text-editor"
MoveToPreviousFoldStartWithSameIndent:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-previous-fold-start-with-same-indent"
  commandScope: "atom-text-editor"
MoveToNextFoldStartWithSameIndent:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-next-fold-start-with-same-indent"
  commandScope: "atom-text-editor"
MoveToPreviousFoldEnd:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-previous-fold-end"
  commandScope: "atom-text-editor"
MoveToNextFoldEnd:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-next-fold-end"
  commandScope: "atom-text-editor"
MoveToPreviousFunction:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-previous-function"
  commandScope: "atom-text-editor"
MoveToNextFunction:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-next-function"
  commandScope: "atom-text-editor"
MoveToPositionByScope:
  file: "./motion"
MoveToPreviousString:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-previous-string"
  commandScope: "atom-text-editor"
MoveToNextString:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-next-string"
  commandScope: "atom-text-editor"
MoveToPreviousNumber:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-previous-number"
  commandScope: "atom-text-editor"
MoveToNextNumber:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-next-number"
  commandScope: "atom-text-editor"
MoveToNextOccurrence:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-next-occurrence"
  commandScope: "atom-text-editor.vim-mode-plus.has-occurrence"
MoveToPreviousOccurrence:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-previous-occurrence"
  commandScope: "atom-text-editor.vim-mode-plus.has-occurrence"
MoveToPair:
  file: "./motion"
  commandName: "vim-mode-plus:move-to-pair"
  commandScope: "atom-text-editor"
SearchBase:
  file: "./motion-search"
Search:
  file: "./motion-search"
  commandName: "vim-mode-plus:search"
  commandScope: "atom-text-editor"
SearchBackwards:
  file: "./motion-search"
  commandName: "vim-mode-plus:search-backwards"
  commandScope: "atom-text-editor"
SearchCurrentWord:
  file: "./motion-search"
  commandName: "vim-mode-plus:search-current-word"
  commandScope: "atom-text-editor"
SearchCurrentWordBackwards:
  file: "./motion-search"
  commandName: "vim-mode-plus:search-current-word-backwards"
  commandScope: "atom-text-editor"
TextObject:
  file: "./text-object"
Word:
  file: "./text-object"
AWord:
  file: "./text-object"
  commandName: "vim-mode-plus:a-word"
  commandScope: "atom-text-editor"
InnerWord:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-word"
  commandScope: "atom-text-editor"
WholeWord:
  file: "./text-object"
AWholeWord:
  file: "./text-object"
  commandName: "vim-mode-plus:a-whole-word"
  commandScope: "atom-text-editor"
InnerWholeWord:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-whole-word"
  commandScope: "atom-text-editor"
SmartWord:
  file: "./text-object"
ASmartWord:
  file: "./text-object"
  commandName: "vim-mode-plus:a-smart-word"
  commandScope: "atom-text-editor"
InnerSmartWord:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-smart-word"
  commandScope: "atom-text-editor"
Subword:
  file: "./text-object"
ASubword:
  file: "./text-object"
  commandName: "vim-mode-plus:a-subword"
  commandScope: "atom-text-editor"
InnerSubword:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-subword"
  commandScope: "atom-text-editor"
Pair:
  file: "./text-object"
APair:
  file: "./text-object"
AnyPair:
  file: "./text-object"
AAnyPair:
  file: "./text-object"
  commandName: "vim-mode-plus:a-any-pair"
  commandScope: "atom-text-editor"
InnerAnyPair:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-any-pair"
  commandScope: "atom-text-editor"
AnyPairAllowForwarding:
  file: "./text-object"
AAnyPairAllowForwarding:
  file: "./text-object"
  commandName: "vim-mode-plus:a-any-pair-allow-forwarding"
  commandScope: "atom-text-editor"
InnerAnyPairAllowForwarding:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-any-pair-allow-forwarding"
  commandScope: "atom-text-editor"
AnyQuote:
  file: "./text-object"
AAnyQuote:
  file: "./text-object"
  commandName: "vim-mode-plus:a-any-quote"
  commandScope: "atom-text-editor"
InnerAnyQuote:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-any-quote"
  commandScope: "atom-text-editor"
Quote:
  file: "./text-object"
DoubleQuote:
  file: "./text-object"
ADoubleQuote:
  file: "./text-object"
  commandName: "vim-mode-plus:a-double-quote"
  commandScope: "atom-text-editor"
InnerDoubleQuote:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-double-quote"
  commandScope: "atom-text-editor"
SingleQuote:
  file: "./text-object"
ASingleQuote:
  file: "./text-object"
  commandName: "vim-mode-plus:a-single-quote"
  commandScope: "atom-text-editor"
InnerSingleQuote:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-single-quote"
  commandScope: "atom-text-editor"
BackTick:
  file: "./text-object"
ABackTick:
  file: "./text-object"
  commandName: "vim-mode-plus:a-back-tick"
  commandScope: "atom-text-editor"
InnerBackTick:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-back-tick"
  commandScope: "atom-text-editor"
CurlyBracket:
  file: "./text-object"
ACurlyBracket:
  file: "./text-object"
  commandName: "vim-mode-plus:a-curly-bracket"
  commandScope: "atom-text-editor"
InnerCurlyBracket:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-curly-bracket"
  commandScope: "atom-text-editor"
ACurlyBracketAllowForwarding:
  file: "./text-object"
  commandName: "vim-mode-plus:a-curly-bracket-allow-forwarding"
  commandScope: "atom-text-editor"
InnerCurlyBracketAllowForwarding:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-curly-bracket-allow-forwarding"
  commandScope: "atom-text-editor"
SquareBracket:
  file: "./text-object"
ASquareBracket:
  file: "./text-object"
  commandName: "vim-mode-plus:a-square-bracket"
  commandScope: "atom-text-editor"
InnerSquareBracket:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-square-bracket"
  commandScope: "atom-text-editor"
ASquareBracketAllowForwarding:
  file: "./text-object"
  commandName: "vim-mode-plus:a-square-bracket-allow-forwarding"
  commandScope: "atom-text-editor"
InnerSquareBracketAllowForwarding:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-square-bracket-allow-forwarding"
  commandScope: "atom-text-editor"
Parenthesis:
  file: "./text-object"
AParenthesis:
  file: "./text-object"
  commandName: "vim-mode-plus:a-parenthesis"
  commandScope: "atom-text-editor"
InnerParenthesis:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-parenthesis"
  commandScope: "atom-text-editor"
AParenthesisAllowForwarding:
  file: "./text-object"
  commandName: "vim-mode-plus:a-parenthesis-allow-forwarding"
  commandScope: "atom-text-editor"
InnerParenthesisAllowForwarding:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-parenthesis-allow-forwarding"
  commandScope: "atom-text-editor"
AngleBracket:
  file: "./text-object"
AAngleBracket:
  file: "./text-object"
  commandName: "vim-mode-plus:a-angle-bracket"
  commandScope: "atom-text-editor"
InnerAngleBracket:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-angle-bracket"
  commandScope: "atom-text-editor"
AAngleBracketAllowForwarding:
  file: "./text-object"
  commandName: "vim-mode-plus:a-angle-bracket-allow-forwarding"
  commandScope: "atom-text-editor"
InnerAngleBracketAllowForwarding:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-angle-bracket-allow-forwarding"
  commandScope: "atom-text-editor"
Tag:
  file: "./text-object"
ATag:
  file: "./text-object"
  commandName: "vim-mode-plus:a-tag"
  commandScope: "atom-text-editor"
InnerTag:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-tag"
  commandScope: "atom-text-editor"
Paragraph:
  file: "./text-object"
AParagraph:
  file: "./text-object"
  commandName: "vim-mode-plus:a-paragraph"
  commandScope: "atom-text-editor"
InnerParagraph:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-paragraph"
  commandScope: "atom-text-editor"
Indentation:
  file: "./text-object"
AIndentation:
  file: "./text-object"
  commandName: "vim-mode-plus:a-indentation"
  commandScope: "atom-text-editor"
InnerIndentation:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-indentation"
  commandScope: "atom-text-editor"
Comment:
  file: "./text-object"
AComment:
  file: "./text-object"
  commandName: "vim-mode-plus:a-comment"
  commandScope: "atom-text-editor"
InnerComment:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-comment"
  commandScope: "atom-text-editor"
CommentOrParagraph:
  file: "./text-object"
ACommentOrParagraph:
  file: "./text-object"
  commandName: "vim-mode-plus:a-comment-or-paragraph"
  commandScope: "atom-text-editor"
InnerCommentOrParagraph:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-comment-or-paragraph"
  commandScope: "atom-text-editor"
Fold:
  file: "./text-object"
AFold:
  file: "./text-object"
  commandName: "vim-mode-plus:a-fold"
  commandScope: "atom-text-editor"
InnerFold:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-fold"
  commandScope: "atom-text-editor"
Function:
  file: "./text-object"
AFunction:
  file: "./text-object"
  commandName: "vim-mode-plus:a-function"
  commandScope: "atom-text-editor"
InnerFunction:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-function"
  commandScope: "atom-text-editor"
Arguments:
  file: "./text-object"
AArguments:
  file: "./text-object"
  commandName: "vim-mode-plus:a-arguments"
  commandScope: "atom-text-editor"
InnerArguments:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-arguments"
  commandScope: "atom-text-editor"
CurrentLine:
  file: "./text-object"
ACurrentLine:
  file: "./text-object"
  commandName: "vim-mode-plus:a-current-line"
  commandScope: "atom-text-editor"
InnerCurrentLine:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-current-line"
  commandScope: "atom-text-editor"
Entire:
  file: "./text-object"
AEntire:
  file: "./text-object"
  commandName: "vim-mode-plus:a-entire"
  commandScope: "atom-text-editor"
InnerEntire:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-entire"
  commandScope: "atom-text-editor"
Empty:
  file: "./text-object"
LatestChange:
  file: "./text-object"
ALatestChange:
  file: "./text-object"
  commandName: "vim-mode-plus:a-latest-change"
  commandScope: "atom-text-editor"
InnerLatestChange:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-latest-change"
  commandScope: "atom-text-editor"
SearchMatchForward:
  file: "./text-object"
  commandName: "vim-mode-plus:search-match-forward"
  commandScope: "atom-text-editor"
SearchMatchBackward:
  file: "./text-object"
  commandName: "vim-mode-plus:search-match-backward"
  commandScope: "atom-text-editor"
PreviousSelection:
  file: "./text-object"
  commandName: "vim-mode-plus:previous-selection"
  commandScope: "atom-text-editor"
PersistentSelection:
  file: "./text-object"
APersistentSelection:
  file: "./text-object"
  commandName: "vim-mode-plus:a-persistent-selection"
  commandScope: "atom-text-editor"
InnerPersistentSelection:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-persistent-selection"
  commandScope: "atom-text-editor"
VisibleArea:
  file: "./text-object"
AVisibleArea:
  file: "./text-object"
  commandName: "vim-mode-plus:a-visible-area"
  commandScope: "atom-text-editor"
InnerVisibleArea:
  file: "./text-object"
  commandName: "vim-mode-plus:inner-visible-area"
  commandScope: "atom-text-editor"
MiscCommand:
  file: "./misc-command"
Mark:
  file: "./misc-command"
  commandName: "vim-mode-plus:mark"
  commandScope: "atom-text-editor"
ReverseSelections:
  file: "./misc-command"
  commandName: "vim-mode-plus:reverse-selections"
  commandScope: "atom-text-editor"
BlockwiseOtherEnd:
  file: "./misc-command"
  commandName: "vim-mode-plus:blockwise-other-end"
  commandScope: "atom-text-editor"
Undo:
  file: "./misc-command"
  commandName: "vim-mode-plus:undo"
  commandScope: "atom-text-editor"
Redo:
  file: "./misc-command"
  commandName: "vim-mode-plus:redo"
  commandScope: "atom-text-editor"
FoldCurrentRow:
  file: "./misc-command"
  commandName: "vim-mode-plus:fold-current-row"
  commandScope: "atom-text-editor"
UnfoldCurrentRow:
  file: "./misc-command"
  commandName: "vim-mode-plus:unfold-current-row"
  commandScope: "atom-text-editor"
ToggleFold:
  file: "./misc-command"
  commandName: "vim-mode-plus:toggle-fold"
  commandScope: "atom-text-editor"
FoldCurrentRowRecursivelyBase:
  file: "./misc-command"
FoldCurrentRowRecursively:
  file: "./misc-command"
  commandName: "vim-mode-plus:fold-current-row-recursively"
  commandScope: "atom-text-editor"
UnfoldCurrentRowRecursively:
  file: "./misc-command"
  commandName: "vim-mode-plus:unfold-current-row-recursively"
  commandScope: "atom-text-editor"
ToggleFoldRecursively:
  file: "./misc-command"
  commandName: "vim-mode-plus:toggle-fold-recursively"
  commandScope: "atom-text-editor"
UnfoldAll:
  file: "./misc-command"
  commandName: "vim-mode-plus:unfold-all"
  commandScope: "atom-text-editor"
FoldAll:
  file: "./misc-command"
  commandName: "vim-mode-plus:fold-all"
  commandScope: "atom-text-editor"
UnfoldNextIndentLevel:
  file: "./misc-command"
  commandName: "vim-mode-plus:unfold-next-indent-level"
  commandScope: "atom-text-editor"
FoldNextIndentLevel:
  file: "./misc-command"
  commandName: "vim-mode-plus:fold-next-indent-level"
  commandScope: "atom-text-editor"
ReplaceModeBackspace:
  file: "./misc-command"
  commandName: "vim-mode-plus:replace-mode-backspace"
  commandScope: "atom-text-editor.vim-mode-plus.insert-mode.replace"
ScrollWithoutChangingCursorPosition:
  file: "./misc-command"
ScrollDown:
  file: "./misc-command"
  commandName: "vim-mode-plus:scroll-down"
  commandScope: "atom-text-editor"
ScrollUp:
  file: "./misc-command"
  commandName: "vim-mode-plus:scroll-up"
  commandScope: "atom-text-editor"
ScrollCursor:
  file: "./misc-command"
ScrollCursorToTop:
  file: "./misc-command"
  commandName: "vim-mode-plus:scroll-cursor-to-top"
  commandScope: "atom-text-editor"
ScrollCursorToTopLeave:
  file: "./misc-command"
  commandName: "vim-mode-plus:scroll-cursor-to-top-leave"
  commandScope: "atom-text-editor"
ScrollCursorToBottom:
  file: "./misc-command"
  commandName: "vim-mode-plus:scroll-cursor-to-bottom"
  commandScope: "atom-text-editor"
ScrollCursorToBottomLeave:
  file: "./misc-command"
  commandName: "vim-mode-plus:scroll-cursor-to-bottom-leave"
  commandScope: "atom-text-editor"
ScrollCursorToMiddle:
  file: "./misc-command"
  commandName: "vim-mode-plus:scroll-cursor-to-middle"
  commandScope: "atom-text-editor"
ScrollCursorToMiddleLeave:
  file: "./misc-command"
  commandName: "vim-mode-plus:scroll-cursor-to-middle-leave"
  commandScope: "atom-text-editor"
ScrollCursorToLeft:
  file: "./misc-command"
  commandName: "vim-mode-plus:scroll-cursor-to-left"
  commandScope: "atom-text-editor"
ScrollCursorToRight:
  file: "./misc-command"
  commandName: "vim-mode-plus:scroll-cursor-to-right"
  commandScope: "atom-text-editor"
ActivateNormalModeOnce:
  file: "./misc-command"
  commandName: "vim-mode-plus:activate-normal-mode-once"
  commandScope: "atom-text-editor.vim-mode-plus.insert-mode"
InsertRegister:
  file: "./misc-command"
  commandName: "vim-mode-plus:insert-register"
  commandScope: "atom-text-editor.vim-mode-plus.insert-mode"
InsertLastInserted:
  file: "./misc-command"
  commandName: "vim-mode-plus:insert-last-inserted"
  commandScope: "atom-text-editor.vim-mode-plus.insert-mode"
CopyFromLineAbove:
  file: "./misc-command"
  commandName: "vim-mode-plus:copy-from-line-above"
  commandScope: "atom-text-editor.vim-mode-plus.insert-mode"
CopyFromLineBelow:
  file: "./misc-command"
  commandName: "vim-mode-plus:copy-from-line-below"
  commandScope: "atom-text-editor.vim-mode-plus.insert-mode"
NextTab:
  file: "./misc-command"
  commandName: "vim-mode-plus:next-tab"
  commandScope: "atom-text-editor"
PreviousTab:
  file: "./misc-command"
  commandName: "vim-mode-plus:previous-tab"
  commandScope: "atom-text-editor"
